language: node_js
node_js:
  - "7"
script: npm install && mkdir artefacts && tar -zcvf  artefacts/imbportal-$(git describe --tags --abbrev=0).tar.gz --exclude=./artefacts .
install: true
deploy:
  provider: releases
  api_key:
    secure: "oqh3hEhBeXLyGUJsUqxaK0Vc8M5GNLaZbNSJIzj5PNbs5Z3h11gTGondCt8/XWlAFDUTx5rIOKkqGm3HHofbNEGNnNQc5Pb1FEbU2nPuq4fDaMlolon1EK7iKRxUt0+Z/sb++A0JfkEmL+KGoOm/mC3vguDW0Wr4upUjrD+d8Lrifm1CYnECkoJxfZ3hwsxxS0feHjIJenwC/E152QoLWy9T2K0vTP5hppDukOhWoDKucPdmZJoVaTdD3izvUBZlb8EdvT1Z+zNZtr1BZttrENSLEUE36SxMslWX8jkSM8WV+cN6K3zpy+FCJJrooV2IfXb8odHaw/5qeBIv1pQ4vR0QogMpBBm1yOmXTedyQ1BfPMrtgmHENTn3e/cbUcqPOlfHbbq8wlYIdsauNzIAWBkY+5HTxyYiXUSagtJjRrIqvjE6lCZtY9ZXzYw1USf6WgGK9tow6O6zulxPwvIj8VZzE7IiH83O/mibVnwp9jgFhMkcRd91LNxVkj0UQK5g2RK7x+jyanqPqyYsVPKpr33IhEb46MBumoY2VUJSwal3PXdev5Mfin3fPLFuIt+s5dg4GeWKX3IWoze2450jO0sjZwbPa/Ww7sXVtWPUZmGEVsxlYCbIbXVHG7rYB2SsxX0Rz8KuIdfmIe+zPdx+WN2e6QDL13AkUsNqW26xg7I="
  skip_cleanup: true
  file_glob: true
  file: artefacts/imbportal-*.tar.gz
  draft: false
  overwrite: true
  on:
    tags: true
