language: node_js
node_js:
  - "7"

script:
  - npm install
  - mkdir artifacts
  - |
    GIT_DESCRIBE=$(git describe --tags --abbrev=0)
    tar -czf artifacts/imbportal-${GIT_DESCRIBE}.tar.gz \
      --transform "s/^\./imbportal-${GIT_DESCRIBE}/" \
      --exclude=./artifacts \
      --exclude=./.git \
      .

install: true
deploy:
  provider: releases
  api_key:
    secure: e38TkHQiGuD2//U3mJb/cnmltByr72sS2qpNNmSWkyh6vWjFGZXYfHDgT4BKHPxmbyJ3/D3DySQpw6oo1HpR7GxKmD1zqulUNQf1jedD0biYwxNQf1Ru+LvS4PRPnpDOV8Y0rulQ0qnrc+6hL3/kc1k4RTvSE0GcB/T1K4XXhCGSUh5lcDhtW80q7vq60wrQ4NfiXZZiaoOi2mN0n0WNj6elhKJ1j00EXmVFOwzPrSitR1UXbtEaP72LopegeIBADnQ7sK55uqhAgXvxdwEb1CI5kCWZV7wrnGIVY7UyOGlKyO2wWgoD8okjLDmUkztN8NFF77AzmCiWBwSx/CZklhAxQw1EQssrdQgprOmsZXwgRq/nbD/ASwiXOXQn+lmQ/DcI8lgIbQW6yTK1OQDrlPsG2dOENrT9efltJBocFdRjex+LiYvigxFJeBtNwKsJ14+aYdkoW4hJ5BPeutiGdpWdzG2++Ut0AfdRcatV/UNrxXKqZaXRSb9LY7gboyfUCvstbWPfXZWFSaPOaQezBiyF8P5v4SJ1CPXxT1C9UMeD07VDDJ7WXYeBodJ0Pgbm4JNlB2NKccp57YT2mR/VRgR7SZ1UkQZ7ILLItVLeXbf2jxeFnEP4uXn+fvxAPyaUxGiB87yw1mcK2gZ7N/Ekgn8xqUCv23frX0piBx4BdBU=
  skip_cleanup: true
  file_glob: true
  file: artifacts/imbportal-*.tar.gz
  draft: false
  overwrite: true
  on:
    tags: true
